import React, { useState } from 'react';
import {
  X,
  Sparkles,
  Shield,
  Radio,
  Cpu,
  Code2,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  TrendingUp,
  Activity,
  Layers,
  Copy,
  Check,
  RefreshCw,
  Sliders,
} from 'lucide-react';
import {
  AssessedControl,
  RCSAPayload,
  AISettings,
  AIExecutiveSummary,
  AIRiskRemediationSynthesis,
  AITrendItem,
} from '../types';
import {
  generateAISummary,
  generateAIHeatmapPrediction,
  generateAIRiskRemediationSynthesis,
  generateAITrends,
  getAIEngineLabel,
} from '../utils/aiDashboardEngine';
import { SECTOR_PROFILES } from '../data/sectorProfiles';

interface AICopilotDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  assessment: RCSAPayload;
  targetControl?: AssessedControl | null;
  aiSettings?: AISettings;
  onOpenSettingsModal?: () => void;
  onOpenSettings?: () => void;
  onSelectControlForReview?: (controlId: string) => void;
}

export const AICopilotDrawer: React.FC<AICopilotDrawerProps> = ({
  isOpen,
  onClose,
  assessment,
  targetControl,
  aiSettings,
  onOpenSettingsModal,
  onOpenSettings,
  onSelectControlForReview,
}) => {
  const handleOpenSettings = onOpenSettings || onOpenSettingsModal;
  const [activeTab, setActiveTab] = useState<'hardening' | 'executive' | 'trends'>('hardening');
  const [copiedCode, setCopiedCode] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedHardeningCode, setGeneratedHardeningCode] = useState<string | null>(null);

  if (!isOpen) return null;

  const sector = SECTOR_PROFILES[assessment.organizationProfile.sector] || SECTOR_PROFILES.Technology;

  // Generate specialized Zero-Trust hardening template for target control or top deficiency
  const activeControl = targetControl || assessment.controls.find((c) => c.residualRisk >= 10) || assessment.controls[0];

  const handleGenerateHardening = () => {
    setIsGenerating(true);
    setTimeout(() => {
      if (!activeControl) {
        setIsGenerating(false);
        return;
      }

      const sampleHardening = `// ============================================================================
// ZERO-TRUST POLICY HARDENING SPECIFICATION
// CONTROL: ${activeControl.controlId} - ${activeControl.title}
// DOMAIN: ${activeControl.domain} | SECTOR: ${sector.name}
// GENERATED BY TECHNOSCOPE AI COPILOT (${getAIEngineLabel(aiSettings)})
// ============================================================================

package security.controls.${activeControl.controlId.toLowerCase().replace(/[^a-z0-9]/g, '_')}

import (
    "context"
    "time"
    "github.com/technoscope/audit/v4/enforcer"
    "github.com/technoscope/audit/v4/telemetry"
)

type ${activeControl.controlId.replace(/[^a-zA-Z0-9]/g, '')}Enforcer struct {
    strictMFAEnabled      bool
    maxSessionDuration    time.Duration
    driftToleranceSeconds int
}

func New${activeControl.controlId.replace(/[^a-zA-Z0-9]/g, '')}Enforcer() *${activeControl.controlId.replace(/[^a-zA-Z0-9]/g, '')}Enforcer {
    return &${activeControl.controlId.replace(/[^a-zA-Z0-9]/g, '')}Enforcer{
        strictMFAEnabled:      true,
        maxSessionDuration:    15 * time.Minute,
        driftToleranceSeconds: 0, // Zero tolerance for unauthorized drift
    }
}

// ValidateCompliance enforces automated verification for ${activeControl.title}
func (e *${activeControl.controlId.replace(/[^a-zA-Z0-9]/g, '')}Enforcer) ValidateCompliance(ctx context.Context, principal enforcer.Identity) (bool, error) {
    telemetry.RecordAuditProof("${activeControl.controlId}", principal.ID, time.Now())
    
    // 1. Enforce Contextual Least-Privilege & Step-Up Auth
    if !principal.HasHardwareMFA() {
        return false, enforcer.ErrStepUpMFAEnforcementRequired
    }
    
    // 2. Cryptographic Session Attestation
    if principal.SessionAge() > e.maxSessionDuration {
        return false, enforcer.ErrSessionExpired
    }
    
    return true, nil
}`;
      setGeneratedHardeningCode(sampleHardening);
      setIsGenerating(false);
    }, 400);
  };

  const handleCopyCode = () => {
    if (generatedHardeningCode) {
      navigator.clipboard.writeText(generatedHardeningCode);
      setCopiedCode(true);
      setTimeout(() => setCopiedCode(false), 2000);
    }
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden flex justify-end">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/75 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      />

      {/* Drawer Panel */}
      <div className="relative w-full max-w-2xl bg-[#111111] border-l border-[#262626] h-full shadow-2xl flex flex-col z-10 animate-in slide-in-from-right duration-200">
        {/* Header */}
        <div className="p-5 border-b border-[#262626] bg-[#0c0c0c] flex items-start justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 text-[9px] font-mono font-bold uppercase tracking-wider bg-[#f5ff00] text-black flex items-center gap-1">
                <Sparkles className="w-2.5 h-2.5" />
                AI Security Copilot
              </span>
              <span className="text-[10px] font-mono text-[#888888] flex items-center gap-1">
                <Radio className="w-2.5 h-2.5 text-[#34d399] animate-pulse" />
                {getAIEngineLabel(aiSettings)}
              </span>
            </div>
            <h2 className="text-base sm:text-lg font-syne font-bold uppercase tracking-tight text-white leading-snug">
              Security Intelligence & Hardening
            </h2>
          </div>

          <div className="flex items-center gap-2">
            {onOpenSettingsModal && (
              <button
                onClick={onOpenSettingsModal}
                className="px-2 py-1 text-[9px] font-mono uppercase font-bold border border-[#333333] bg-black text-[#888888] hover:text-[#f5ff00] hover:border-[#f5ff00] transition cursor-pointer"
                title="Change AI Engine Settings"
              >
                Engine Config
              </button>
            )}
            <button
              onClick={onClose}
              className="p-1.5 border border-[#333333] bg-[#1a1a1a] text-[#888888] hover:text-white hover:border-white transition cursor-pointer"
              title="Close Drawer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Drawer Tabs */}
        <div className="flex border-b border-[#262626] bg-[#0d0d0d] px-4 font-mono text-xs">
          <button
            onClick={() => setActiveTab('hardening')}
            className={`py-3 px-4 uppercase font-bold tracking-wider flex items-center gap-1.5 border-b-2 -mb-px transition cursor-pointer ${
              activeTab === 'hardening'
                ? 'border-[#f5ff00] text-[#f5ff00] bg-[#161616]'
                : 'border-transparent text-[#777777] hover:text-white'
            }`}
          >
            <Code2 className="w-3.5 h-3.5" />
            <span>1. Zero-Trust Hardening</span>
          </button>
          <button
            onClick={() => setActiveTab('executive')}
            className={`py-3 px-4 uppercase font-bold tracking-wider flex items-center gap-1.5 border-b-2 -mb-px transition cursor-pointer ${
              activeTab === 'executive'
                ? 'border-[#f5ff00] text-[#f5ff00] bg-[#161616]'
                : 'border-transparent text-[#777777] hover:text-white'
            }`}
          >
            <Shield className="w-3.5 h-3.5" />
            <span>2. Executive Summary</span>
          </button>
          <button
            onClick={() => setActiveTab('trends')}
            className={`py-3 px-4 uppercase font-bold tracking-wider flex items-center gap-1.5 border-b-2 -mb-px transition cursor-pointer ${
              activeTab === 'trends'
                ? 'border-[#f5ff00] text-[#f5ff00] bg-[#161616]'
                : 'border-transparent text-[#777777] hover:text-white'
            }`}
          >
            <TrendingUp className="w-3.5 h-3.5" />
            <span>3. Regulatory Horizon</span>
          </button>
        </div>

        {/* Body Content */}
        <div className="flex-1 overflow-y-auto p-5 space-y-6 text-xs text-white">
          {/* TAB 1: ZERO TRUST HARDENING */}
          {activeTab === 'hardening' && (
            <div className="space-y-4">
              {activeControl && (
                <div className="p-4 bg-black border border-[#262626] space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-xs font-bold text-[#f5ff00]">
                      {activeControl.controlId}: {activeControl.title}
                    </span>
                    <span className="text-[10px] font-mono text-[#888888]">
                      Residual: <strong className="text-white">{activeControl.residualRisk.toFixed(1)}</strong>
                    </span>
                  </div>
                  <p className="text-xs text-[#aaaaaa] font-sans">
                    {activeControl.gapsIdentified || activeControl.discussion}
                  </p>
                </div>
              )}

              <div className="flex items-center justify-between">
                <button
                  onClick={handleGenerateHardening}
                  disabled={isGenerating}
                  className="px-4 py-2 bg-[#f5ff00] text-black hover:bg-yellow-300 font-mono text-xs font-bold uppercase tracking-wider flex items-center gap-1.5 transition cursor-pointer"
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  <span>{isGenerating ? 'Generating Policy...' : 'Generate Enforcement Code'}</span>
                </button>

                {generatedHardeningCode && (
                  <button
                    onClick={handleCopyCode}
                    className="px-3 py-1.5 border border-[#333333] bg-black text-[#f5ff00] hover:border-[#f5ff00] font-mono text-[10px] uppercase font-bold flex items-center gap-1 transition cursor-pointer"
                  >
                    {copiedCode ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    <span>{copiedCode ? 'Copied' : 'Copy Code'}</span>
                  </button>
                )}
              </div>

              {generatedHardeningCode ? (
                <div className="p-3 bg-[#0a0a0a] border border-[#2a2a2a] overflow-x-auto">
                  <pre className="font-mono text-[11px] text-emerald-300 leading-relaxed">
                    {generatedHardeningCode}
                  </pre>
                </div>
              ) : (
                <div className="p-8 border border-dashed border-[#333333] text-center text-[#777777] font-mono">
                  Click "Generate Enforcement Code" to synthesize a complete Zero Trust enforcement policy and technical compensating control for this safeguard.
                </div>
              )}
            </div>
          )}

          {/* TAB 2: EXECUTIVE SUMMARY */}
          {activeTab === 'executive' && (
            <div className="space-y-4">
              <div className="p-4 border border-[#262626] bg-black space-y-3">
                <div className="text-[10px] font-mono uppercase text-[#777777] font-bold">
                  POSTURE EVALUATION SUMMARY
                </div>
                <h4 className="text-base font-bold text-white leading-snug">
                  Target System: {assessment.organizationProfile.targetSystem} ({sector.name})
                </h4>
                <div className="grid grid-cols-2 gap-3 pt-2">
                  <div className="p-3 bg-[#141414] border border-[#222222]">
                    <div className="text-[9px] font-mono uppercase text-[#777777]">Compliance Framework</div>
                    <div className="text-xs font-mono font-bold text-[#f5ff00] mt-0.5">
                      NIST SP 800-53 Rev. 5
                    </div>
                  </div>
                  <div className="p-3 bg-[#141414] border border-[#222222]">
                    <div className="text-[9px] font-mono uppercase text-[#777777]">Assessor In-Charge</div>
                    <div className="text-xs font-mono font-bold text-white mt-0.5">
                      {assessment.organizationProfile.assessorName}
                    </div>
                  </div>
                </div>
              </div>

              <div className="p-4 border border-[#262626] bg-[#141414] space-y-2">
                <span className="text-[10px] font-mono uppercase font-bold text-[#f5ff00] tracking-wider">
                  Top Volatile Controls Watchlist
                </span>
                <div className="space-y-1.5">
                  {assessment.controls
                    .filter((c) => c.residualRisk >= 8)
                    .slice(0, 4)
                    .map((c) => (
                      <div
                        key={c.controlId}
                        onClick={() => {
                          if (onSelectControlForReview) {
                            onSelectControlForReview(c.controlId);
                            onClose();
                          }
                        }}
                        className="flex items-center justify-between p-2.5 bg-black border border-[#2a2a2a] hover:border-[#f5ff00] transition cursor-pointer group"
                      >
                        <div className="min-w-0 pr-2">
                          <span className="font-mono text-xs font-bold text-[#f5ff00] group-hover:underline">
                            {c.controlId}
                          </span>{' '}
                          <span className="text-xs text-white truncate">{c.title}</span>
                        </div>
                        <span className="text-[10px] font-mono font-bold text-rose-400 shrink-0">
                          RR: {c.residualRisk.toFixed(1)}
                        </span>
                      </div>
                    ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: REGULATORY HORIZON */}
          {activeTab === 'trends' && (
            <div className="space-y-3">
              <div className="text-[10px] font-mono uppercase font-bold text-[#f5ff00] tracking-wider">
                Sector Regulatory Directives ({sector.name})
              </div>
              <div className="p-4 border border-[#262626] bg-black space-y-2">
                <div className="text-xs font-bold text-white">
                  Regulatory Frameworks In Effect
                </div>
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {sector.regulatoryFrameworks.map((fw, idx) => (
                    <span
                      key={idx}
                      className="px-2 py-0.5 bg-[#1a1a1a] border border-[#333333] text-[10px] font-mono text-white"
                    >
                      {fw}
                    </span>
                  ))}
                </div>
              </div>
              <div className="p-4 border border-[#262626] bg-black space-y-2">
                <div className="text-xs font-bold text-white">
                  Mandatory Assurance Baseline
                </div>
                <p className="text-xs text-[#aaaaaa] leading-relaxed">
                  {sector.mandatoryOverlays}
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-[#262626] bg-[#0c0c0c] flex items-center justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-[#222222] hover:bg-[#333333] text-white font-mono text-xs font-bold uppercase tracking-wider transition cursor-pointer"
          >
            Close Copilot
          </button>
        </div>
      </div>
    </div>
  );
};
